version: '3'
services:
  app:
    build: .
    depends_on:
      - monitoring_app
    volumes:
      - .:/code
      - ./results:/app/results
      - ./processing_result:/app/processing_result
    command: python script.py
  monitoring_app:
    build: .
    ports:
      - 8081:8081
    command: python app.py
    depends_on:
      - prometheus
      - grafana
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
    restart: always
  grafana:
    image: grafana/grafana:5.0.4
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

