version: '2'
services:
  app:
    build: .
    container_name: 'app'
    hostname: app
    environment:
    - MONGO_URL=mongodb://mongodb:27017/
    links:
    - mongodb
    - redis
    depends_on:
    - mongodb
    - redis
    volumes:
    - .:/code
    ports:
    - 8081:8081
    command: >
      bash -c 'python monitoring/app.py'
  redis:
    image: redis:5.0.1
    container_name: 'redis'
    hostname: 'redis'
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    volumes:
    - ./docker_data/redis:/docker_data/redis
    ports:
    - 6379
    command: redis-server
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
    - MONGO_DATA_DIR=/docker_data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - ./docker_data/db:/docker_data/db
    ports:
    - 27017
    command: mongod --smallfiles --dbpath=/docker_data/db
