version: '2'
services:
  app:
    build: .
    container_name: 'app'
    hostname: app
    depends_on:
    - mongodb
    - redis
    volumes:
    - .:/code
    ports:
    - 8080:81
  redis:
    image: redis:5.0.1
    container_name: 'redis'
    hostname: "redis"
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    volumes:
    - ./data/redis:/data/redis
    ports:
    - 6379
    command: redis-server
  mongodb:
    image: bitnami/mongodb:latest
    container_name: 'mongodb'
    ports:
    - 27017
    networks:
    - app-tier

networks:
  app-tier:
    driver: bridge

