version: '3'
services:
  app:
    build: .
#    depends_on:
#      - prometheus
#      - grafana
    command: python manage.py
    ports:
      - 8080:8080
    volumes:
      - .:/code
      - ./results:/app/results
      - ./processing_result:/app/processing_result
#  prometheus:
#    image: prom/prometheus:v2.1.0
#    volumes:
#      - prometheus_data:/prometheus
#      - ./prometheus/:/etc/prometheus/
#    ports:
#      - 9090:9090
#  grafana:
#    image: grafana/grafana:5.0.4
#    ports:
#      - 3000:3000
#    volumes:
#      - grafana_data:/var/lib/grafana
#
#volumes:
#  grafana_data:
#  prometheus_data:

