version: '3'
services:
  app:
    build: .
    environment:
    - MONGO_URL=mongodb://mongodb:27017/
    depends_on:
    - monitoring_app
    volumes:
    - ./results:/app/results
    - ./processing_result:/app/processing_result
    image: arthur264/music:tagname
    command: python script.py
  monitoring_app:
    build: .
    environment:
    - MONGO_URL=mongodb://mongodb:27017/
    ports:
    - 8081:8081
    command: python app.py
    image: arthur264/music:tagname
    depends_on:
    - mongodb
    - redis
  redis:
    image: redis:5.0.1
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    ports:
    - 6379
    command: redis-server
  mongodb:
    image: mongo:latest
    environment:
    - MONGO_DATA_DIR=/docker_data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - ./docker_data/db:/docker_data/db
    ports:
    - 27017
    command: mongod --smallfiles --dbpath=/docker_data/db

