version: '2'
services:
  app:
    build: .
    container_name: 'app'
    hostname: app
    environment:
    - MONGO_URL=mongodb://mongo:27017/
    depends_on:
    - mongodb
    - redis
    volumes:
    - .:/code
    ports:
    - 8080:81
    command: python code/script.py
  redis:
    image: redis:5.0.1
    container_name: 'redis'
    hostname: 'redis'
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    volumes:
    - ./data/redis:/data/redis
    ports:
    - 6379
    command: redis-server
  mongodb:
    image: bitnami/mongodb:latest
    container_name: 'mongodb'
    hostname: 'mongo'
    volumes:
    - mongodata:/data/db
    ports:
    - 27017
volumes:
  mongodata: