global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'test-course'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8081']
