ROBOTSTXT_OBEY = True
CONCURRENT_REQUESTS = 100
CONCURRENT_REQUESTS_PER_IP = 8

LOG_LEVEL = 'INFO'
LOG_ENABLED = False

RETRY_TIMES = 5
ITEM_PIPELINES = {
    'crawler.pipelines.MusicPipeline': 800
}
